const symptomMapping = {
    "asam lambung": 0,
    "batuk": 1,
    "bercak di tenggorokan": 2,
    "berjalan sakit": 3,
    "berkeringat": 4,
    "bersin terus menerus": 5,
    "bibir mengering dan kesemutan": 6,
    "bicara tidak jelas": 7,
    "bintik-bintik merah di seluruh tubuh": 8,
    "dahak": 9,
    "dahak berkarat": 10,
    "dahak berlendir": 11,
    "darah dalam dahak": 12,
    "debu seperti perak": 13,
    "dehidrasi": 14,
    "demam ringan": 15,
    "demam tinggi": 16,
    "depresi": 17,
    "detak jantung cepat": 18,
    "diare": 19,
    "gagal hati akut": 20,
    "gangguan pencernaan": 21,
    "gangguan visual": 22,
    "gatal internal": 23,
    "gerakan berputar": 24,
    "haid tidak normal": 25,
    "hidung meler": 26,
    "hubungan di luar nikah": 27,
    "iritasi pada anus": 28,
    "iritasi tenggorokan": 29,
    "jantung berdebar": 30,
    "jerawat berisi nanah": 31,
    "kadar gula tidak teratur": 32,
    "kaki bengkak": 33,
    "kecemasan": 34,
    "kedinginan": 35,
    "kegelisahan": 36,
    "kegoyahan": 37,
    "kehilangan keseimbangan": 38,
    "kehilangan nafsu makan": 39,
    "kehilangan penciuman": 40,
    "kekakuan gerakan": 41,
    "kelebihan cairan": 42,
    "kelelahan": 43,
    "kelemahan otot": 44,
    "kelemahan pada salah satu sisi tubuh": 45,
    "kelemahan pada tungkai": 46,
    "kelenjar getah bening membengkak": 47,
    "kelesuan": 48,
    "keluarnya gas": 49,
    "kemacetan": 50,
    "kemerahan pada mata": 51,
    "kenaikan berat badan": 52,
    "kerak kuning": 53,
    "ketidaknyamanan kandung kemih": 54,
    "koma": 55,
    "komedo": 56,
    "kram": 57,
    "kuku rapuh": 58,
    "kulit kekuningan": 59,
    "kurangnya konsentrasi": 60,
    "leher kaku": 61,
    "letusan kulit nodal": 62,
    "luka merah di sekitar hidung": 63,
    "malaise": 64,
    "mata berair": 65,
    "mata cekung": 66,
    "mata menguning": 67,
    "melepuh": 68,
    "memar": 69,
    "menerima suntikan yang tidak steril": 70,
    "menerima transfusi darah": 71,
    "menggigil": 72,
    "mual": 73,
    "mudah tersinggung": 74,
    "nafsu makan meningkat": 75,
    "nyeri dada": 76,
    "nyeri di belakang mata": 77,
    "nyeri di daerah anus": 78,
    "nyeri lutut": 79,
    "nyeri otot": 80,
    "nyeri saat buang air besar": 81,
    "nyeri sendi": 82,
    "nyeri sendi pinggul": 83,
    "obesitas": 84,
    "pembengkakan ekstremitas": 85,
    "pembengkakan perut": 86,
    "pembesaran tiroid": 87,
    "pembuluh darah bengkak": 88,
    "pembuluh darah yang menonjol di betis": 89,
    "pendarahan perut": 90,
    "pengecilan otot": 91,
    "pengelupasan kulit": 92,
    "penglihatan kabur dan terdistorsi": 93,
    "penurunan berat badan": 94,
    "penyok kecil di kuku": 95,
    "perasaan terus menerus dari air seni": 96,
    "perubahan suasana hati": 97,
    "perut kembung": 98,
    "poliuria": 99,
    "pusing": 100,
    "radang kuku": 101,
    "rasa lapar yang berlebihan": 102,
    "rasa terbakar saat berkemih": 103,
    "riwayat keluarga": 104,
    "riwayat konsumsi alkohol": 105,
    "ruam kulit": 106,
    "sakit kepala": 107,
    "sakit leher": 108,
    "sakit perut": 109,
    "sakit punggung": 110,
    "sariawan di lidah": 111,
    "scurring": 112,
    "sembelit": 113,
    "sendi bengkak": 114,
    "sesak napas": 115,
    "tampilan beracun (tifus)": 116,
    "tangan dan kaki dingin": 117,
    "tekanan sinus": 118,
    "tinja berdarah": 119,
    "urin berwarna gelap": 120,
    "urine berwarna kuning": 121,
    "wajah dan mata bengkak": 122,
    "0": 123,
    "bau busuk dari urin": 124,
    "bercak buang air kecil": 125,
    "bercak diskromik": 126,
    "gatal": 127,
    "muntah": 128,
    "nyeri perut bagian atas": 129,
    "perubahan sensorium": 130,
    "sakit perut bagian tengah": 131
};

const convertSymptomsToNumeric = (symptoms) => {
    let numericSymptoms = Array(Object.keys(symptomMapping).length).fill(0);
    symptoms.forEach(symptom => {
        if (symptomMapping.hasOwnProperty(symptom.trim())) {
            numericSymptoms[symptomMapping[symptom.trim()]] = 1;
        }
    });
    return numericSymptoms;
};

module.exports = { convertSymptomsToNumeric };